### ISSUE TITLE
Groups which own topics cannot be deleted

### ISSUE THREAD

**Issue by cnweaver** [scimma/scimma-admin#45]
Trying to delete any group which owns at least one topic triggers the following exception:
```
Request Method: POST
Request URL: https://admin.dev.hop.scimma.org/hopauth/delete_group

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "./hopskotch_auth/views.py", line 234, in delete_group
    group.delete()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 940, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/deletion.py", line 245, in collect
    field.remote_field.on_delete(self, field, sub_objs, self.using)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/deletion.py", line 16, in CASCADE
    collector.collect(sub_objs, source=field.remote_field.model,
  File "/usr/local/lib/python3.8/site-packages/django/db/models/deletion.py", line 245, in collect
    field.remote_field.on_delete(self, field, sub_objs, self.using)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/deletion.py", line 16, in CASCADE
    collector.collect(sub_objs, source=field.remote_field.model,
  File "/usr/local/lib/python3.8/site-packages/django/db/models/deletion.py", line 196, in collect
    new_objs = self.add(objs, source, nullable,
  File "/usr/local/lib/python3.8/site-packages/django/db/models/deletion.py", line 95, in add
    if obj not in instances:
  File "./hopskotch_auth/models.py", line 343, in __hash__
    return hash((self.principal, self.topic, self.operation))
  File "/usr/local/lib/python3.8/site-packages/django_enumfield/db/fields.py", line 135, in get_enum
    return getattr(self, private_att_name)

Exception Type: AttributeError at /hopauth/delete_group
Exception Value: 'GroupKafkaPermission' object has no attribute '_enum_operation'
```

Due to our various deletion cascading settings, to delete the group, the topic must be deleted, and this requires deleting the `GroupKafkaPermission` which represents the group's access to its own topic (so for each topic there is always at least this one permission). While Django is rummaging around for all of the things it needs to delete, `collect` gathers them in a `set` to avoid recording duplicates. This triggers using our custom `__hash__` implementation, which fails because only some of the fields of the object on which it is called have actually been fetched from the database. The `has no attribute` results from the fact that Django uses the rather ugly trick of only creating field attributes on model objects when it has fetched the data to store in them. 

So, this is happening because 1) Django is taking a shortcut and working on a partial object, which it assumes is sufficient because it has fetched the primary key, which is all that its default `__hash__` implementation uses and 2) we added our own `__hash__` which uses the other fields of the object (because we use it to enforce a more complex uniqueness constraint). Because of our uniqueness constraint, our `__hash__` will do the correct thing in this situation, if all of the data it needs is present. As a result, a hacky fix is to insert a call to `refresh_from_db` into `__hash__` to force the necessary field(s) to be present. This is _really_ ugly, and seems like it can result in a lot of extra requests to the database, most of which are not needed. (`self.refresh_from_db(fields=self.get_deferred_fields())` seems like it might be less inefficient, but this appears to still fetch more than is needed in practice.)

The other option is to not supply our own `GroupKafkaPermission.__hash__`. Unfortunately, we do not have a sufficently detailed test suite to indicate exactly what our existing `__hash__` implementation is being used for. It's probably to address the issue that we want to enforce that we do not create identical duplicate permissions and the standard Django `__hash__` is not useful for this because it will always consider semantically duplicate objects different due to their different primary keys (which are after all, unique). This requires further investigation.

**Comment by cnweaver** [comment]
The implementation of `__hash__` turns out to be required as a result of implementing `__eq__` since "A class that overrides __eq__() and does not define __hash__() will have its __hash__() implicitly set to None." ([python datamode referencel](https://docs.python.org/3/reference/datamodel.html#object.__hash__)). Furthermore, using `__hash__ = models.Model.__hash__` merely shifts where the original problem occurs, as applying the `not in` operator to test for a `GroupKafkaPermission`'s presence in a set also calls `__eq__` which crashes exactly as `__hash__` did due to the object being only partially valid.

**Comment by spenczar** [comment]
Why do we implement `__eq__`? Django implements it for us as a primary key equality check, which seems to be often correct. Maybe we could implement a different method, something like `def equivalent_to(self, other)`?

**Comment by cnweaver** [comment]
We had this, but decided to change it during one of our code reviews: https://github.com/scimma/scimma-admin/pull/16#discussion_r552104772 . It seems we should revert that, as there turn out to be more serious consequences than we realized.

**Comment by spenczar** [comment]
Indeed, mea culpa!
