### ISSUE TITLE
Support RFC 7804 Auth

### ISSUE THREAD

**Issue by cnweaver** [scimma/scimma-admin#63]
https://datatracker.ietf.org/doc/html/rfc7804

The home-brewed token mechanism we already have is good for clients which make large batches of requests on behalf of the same user (e.g. Hermes). RFC 7804 is a standard which it may be easier for client tools to use, and may be more convenient for clients which want to make single requests.

**Comment by Neustradamus** [comment]
@cnweaver: Good job for SCRAM!

Linked to:
- https://github.com/scram-sasl/info/issues/1
- https://github.com/scimma/scimma-admin/issues/63
- https://github.com/scimma/scimma-admin/pull/64
